name: Run Solutions

on:
  push:
  pull_request:

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.14"
      - name: Run all Python solutions
        run: |
          find . -name "solution.py" -print -exec python3 {} \;

  javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: "24"
      - name: Run all JavaScript solutions
        run: |
          find . -name "solution.js" -print -exec node {} \;

  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: "1.22"
      - name: Run all Go solutions
        run: |
          find . -name "solution.go" | while read -r f; do
            echo "Running $f"
            go run "$f"
          done

  csharp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-dotnet@v7
        with:
          dotnet-version: "10.0.x"
      - name: Install dotnet-script
        run: dotnet tool install -g dotnet-script
      - name: Run all C# solutions
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          find . -name "solution.cs" | while read -r f; do
            echo "Running $f"
            dotnet script "$f"
          done
